import type { Verse } from "./index"

export const amorVerses: Verse[] = [
  { ref: "1 João 4:8", text: "Quem não ama não conhece a Deus, porque Deus é amor." },
  { ref: "João 3:16", text: "Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna." },
  { ref: "1 Coríntios 13:13", text: "Assim, permanecem agora estes três: a fé, a esperança e o amor. O maior deles, porém, é o amor." },
  { ref: "1 Coríntios 13:4-7", text: "O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha. Não maltrata, não procura seus próprios interesses, não se ira facilmente, não guarda rancor. O amor não se alegra com a injustiça, mas se alegra com a verdade. Tudo sofre, tudo crê, tudo espera, tudo suporta." },
  { ref: "Romanos 13:10", text: "O amor não pratica o mal contra o próximo. Portanto, o amor é o cumprimento da lei." },
  { ref: "Colossenses 3:14", text: "Acima de tudo, porém, revistam-se do amor, que é o elo perfeito." },
  { ref: "1 João 4:16", text: "Assim conhecemos o amor que Deus tem por nós e confiamos nesse amor. Deus é amor. Todo aquele que permanece no amor permanece em Deus, e Deus nele." },
  { ref: "1 João 4:18", text: "No amor não há medo; ao contrário, o perfeito amor expulsa o medo, porque o medo supõe castigo. Aquele que tem medo não está aperfeiçoado no amor." },
  { ref: "1 João 4:9-10", text: "Foi assim que Deus manifestou o seu amor entre nós: enviou o seu Filho Unigênito ao mundo, para que pudéssemos viver por meio dele. Nisto consiste o amor: não em que nós tenhamos amado a Deus, mas em que ele nos amou e enviou seu Filho como propiciação pelos nossos pecados." },
  { ref: "1 João 4:7", text: "Amados, amemo-nos uns aos outros, pois o amor procede de Deus. Aquele que ama é nascido de Deus e conhece a Deus." },
  { ref: "1 João 4:11", text: "Amados, visto que Deus assim nos amou, nós também devemos amar-nos uns aos outros." },
  { ref: "1 João 3:16", text: "Nisto conhecemos o que é o amor: Jesus Cristo deu a sua vida por nós; e devemos dar a nossa vida pelos irmãos." },
  { ref: "1 João 3:18", text: "Filhinhos, não amemos de palavra nem de boca, mas em ação e em verdade." },
  { ref: "1 João 3:14", text: "Sabemos que já passamos da morte para a vida porque amamos nossos irmãos. Quem não ama permanece na morte." },
  { ref: "1 João 4:12", text: "Ninguém jamais viu a Deus; se nos amarmos uns aos outros, Deus permanece em nós, e o seu amor está aperfeiçoado em nós." },
  { ref: "1 João 5:3", text: "Porque nisto consiste o amor a Deus: em obedecer aos seus mandamentos. E os seus mandamentos não são pesados." },
  { ref: "João 15:9-10", text: "Como o Pai me amou, assim eu os amei; permaneçam no meu amor. Se vocês obedecerem aos meus mandamentos, permanecerão no meu amor." },
  { ref: "João 15:13", text: "Ninguém tem maior amor do que aquele que dá a sua vida pelos seus amigos." },
  { ref: "Romanos 5:8", text: "Mas Deus demonstra seu amor por nós: Cristo morreu em nosso favor quando ainda éramos pecadores." },
  { ref: "Gálatas 2:20", text: "Já fui crucificado com Cristo, e vivo, não mais eu, mas Cristo vive em mim; e a vida que agora vivo no corpo, vivo-a pela fé no Filho de Deus, que me amou e se entregou por mim." },
  { ref: "Romanos 8:38-39", text: "Pois estou convencido de que nem morte nem vida, nem anjos nem demônios, nem presente nem futuro, nem poderes, nem altura nem profundidade, nem qualquer outra coisa na criação será capaz de nos separar do amor de Deus que está em Cristo Jesus, nosso Senhor." },
  { ref: "Efésios 5:25", text: "Maridos, amem suas mulheres, assim como Cristo amou a igreja e se entregou por ela." },
  { ref: "Efésios 5:2", text: "Vivam em amor, como também Cristo nos amou e se entregou por nós como oferta e sacrifício de aroma agradável a Deus." },
  { ref: "Efésios 3:17-19", text: "Que Cristo habite no coração de vocês mediante a fé; e oro para que vocês, arraigados e alicerçados em amor, possam compreender o amor de Cristo, que excede todo entendimento." },
  { ref: "Filipenses 1:9-11", text: "Esta é a minha oração: que o amor de vocês aumente cada vez mais em conhecimento e em toda a percepção." },
  { ref: "Romanos 12:9", text: "O amor deve ser sincero. Odeiem o que é mau; apeguem-se ao que é bom." },
  { ref: "Romanos 12:10", text: "Dediquem-se uns aos outros com amor fraternal. Prefiram dar honra aos outros mais do que a vocês." },
  { ref: "Romanos 13:8", text: "Não devam nada a ninguém, a não ser o amor de uns pelos outros, pois quem ama seu próximo tem cumprido a lei." },
  { ref: "Gálatas 5:14", text: "Pois toda a Lei se resume num só mandamento: ‘Ame o seu próximo como a si mesmo’." },
  { ref: "2 Timóteo 1:7", text: "Pois Deus não nos deu espírito de covardia, mas de poder, de amor e de equilíbrio." },
  { ref: "1 Pedro 4:8", text: "Sobretudo, amem-se sinceramente uns aos outros, porque o amor perdoa muitíssimos pecados." },
  { ref: "Provérbios 10:12", text: "O ódio provoca dissensão, mas o amor cobre todos os pecados." },
  { ref: "Salmos 136:1", text: "Deem graças ao Senhor, porque ele é bom. O seu amor dura para sempre!" },
  { ref: "Salmos 103:8", text: "O Senhor é compassivo e misericordioso, mui paciente e cheio de amor." },
  { ref: "Mateus 22:37-39", text: "‘Ame o Senhor, o seu Deus de todo o seu coração, de toda a sua alma e de todo o seu entendimento.’ Este é o primeiro mandamento. E o segundo é semelhante a ele: ‘Ame o seu próximo como a si mesmo’." },
  { ref: "Lucas 6:35", text: "Amem, porém, os seus inimigos, façam-lhes o bem e emprestem, sem esperar nada em troca. Então a recompensa será grande." },
  { ref: "Mateus 5:44", text: "Mas eu digo: Amem os seus inimigos e orem por aqueles que os perseguem." },
  { ref: "1 Pedro 1:22", text: "Purifiquem suas vidas, obedecendo à verdade, para que tenham amor sincero pelos irmãos; amem-se profundamente de coração." },
  { ref: "2 Coríntios 13:14", text: "A graça do Senhor Jesus Cristo, o amor de Deus e a comunhão do Espírito Santo sejam com todos vocês." },
  { ref: "1 João 4:19", text: "Nós amamos porque ele nos amou primeiro." },
  { ref: "Salmos 63:3", text: "O teu amor é melhor do que a vida! Por isso os meus lábios te exaltarão." },
  { ref: "Cânticos 8:6", text: "Coloque-me como um selo sobre o seu coração, como um selo sobre o seu braço; pois o amor é tão forte quanto a morte." },
  { ref: "Provérbios 3:3-4", text: "Que o amor e a fidelidade jamais o abandonem; prenda-os ao redor do seu pescoço, escreva-os na tábua do seu coração." },
  { ref: "1 Coríntios 2:9", text: "Todavia, como está escrito: 'Olho nenhum viu, ouvido nenhum ouviu, mente nenhuma imaginou o que Deus preparou para aqueles que o amam'." },
  { ref: "Efésios 4:2", text: "Sejam completamente humildes e dóceis, e sejam pacientes, suportando uns aos outros com amor." },
  { ref: "1 Tessalonicenses 3:12", text: "Que o Senhor faça crescer e transbordar o amor que vocês têm uns pelos outros e por todos." },
  { ref: "1 Tessalonicenses 4:9", text: "Quanto ao amor fraternal, não há necessidade de que se escreva, pois vocês mesmos foram ensinados por Deus a se amarem uns aos outros." },
  { ref: "Hebreus 10:24", text: "E consideremo-nos uns aos outros para nos incentivarmos ao amor e às boas obras." },
  { ref: "Hebreus 13:1", text: "Continue o amor fraternal." },
  { ref: "Hebreus 6:10", text: "Deus não é injusto; ele não se esquecerá do trabalho de vocês e do amor que demonstraram por ele." },
  { ref: "1 Pedro 5:14", text: "Saúdem uns aos outros com beijo de amor. Paz a todos vocês que estão em Cristo." },
  { ref: "Judas 1:21", text: "Mantenham-se no amor de Deus, enquanto esperam a misericórdia de nosso Senhor Jesus Cristo para a vida eterna." },
  { ref: "Salmos 86:15", text: "Mas tu, Senhor, és Deus compassivo e misericordioso, muito paciente, rico em amor e fidelidade." },
  { ref: "Salmos 33:5", text: "O Senhor ama a justiça e o direito; a terra está cheia da bondade do Senhor." },
  { ref: "Salmos 145:8", text: "O Senhor é misericordioso e compassivo, paciente e transbordante de amor." },
  { ref: "Salmos 42:8", text: "Conceda-me o Senhor o seu fiel amor de dia; de noite esteja comigo o seu cântico." },
  { ref: "Salmos 25:10", text: "Todos os caminhos do Senhor são amor e fidelidade para com os que cumprem a sua aliança." },
  { ref: "Isaías 54:10", text: "Ainda que os montes sejam abalados e as colinas sejam removidas, ainda assim o meu amor fiel por você não será removido." },
  { ref: "Jeremias 31:3", text: "Eu a amei com amor eterno; com amor leal a atrai." },
  { ref: "Sofonias 3:17", text: "O Senhor, o seu Deus, está em seu meio, poderoso para salvar. Ele se regozijará em você com o seu amor." },
  { ref: "Oséias 11:4", text: "Com laços de bondade e de amor eu os atraí; fui para eles como quem alivia o jugo sobre os seus ombros." },
  { ref: "Miquéias 6:8", text: "O que o Senhor pede de você: pratique a justiça, ame a fidelidade e ande humildemente com o seu Deus." },
  { ref: "Deuteronômio 6:5", text: "Ame o Senhor, o seu Deus, de todo o seu coração, de toda a sua alma e de todas as suas forças." },
  { ref: "Deuteronômio 7:9", text: "Saiba, portanto, que o Senhor, seu Deus, é Deus; ele é o Deus fiel, que mantém a aliança e a bondade por mil gerações àqueles que o amam." },
  { ref: "Deuteronômio 10:19", text: "Amem os estrangeiros, pois vocês mesmos foram estrangeiros no Egito." },
  { ref: "Levítico 19:18", text: "Não se vingue nem guarde rancor, mas ame o seu próximo como a si mesmo. Eu sou o Senhor." },
  { ref: "Josué 22:5", text: "Amem o Senhor, o seu Deus, andem em todos os seus caminhos, obedeçam aos seus mandamentos, sirvam-no e apeguem-se a ele de todo o coração." },
  { ref: "Neemias 1:5", text: "Senhor, Deus dos céus, Deus grande e temível, que manténs a tua aliança de amor aos que te amam e obedecem aos teus mandamentos." },
  { ref: "Salmos 5:7", text: "Mas eu, pelo teu grande amor, entrarei em tua casa; com temor me inclinarei em direção ao teu santo templo." },
  { ref: "Salmos 25:6", text: "Recorda, Senhor, a tua misericórdia e o teu amor, que tens mostrado desde a antiguidade." },
  { ref: "Salmos 36:7", text: "Como é precioso o teu amor, ó Deus! Os homens encontram refúgio à sombra das tuas asas." },
  { ref: "Salmos 89:1", text: "Cantarei para sempre o amor do Senhor; com a minha boca anunciarei a tua fidelidade." },
  { ref: "Salmos 90:14", text: "Satisfaz-nos de manhã com o teu amor leal, e todos os nossos dias cantaremos felizes." },
  { ref: "Salmos 94:18", text: "Quando eu disse: 'Os meus pés escorregaram', o teu amor leal me amparou, Senhor." },
  { ref: "Salmos 119:64", text: "A terra está cheia do teu amor, Senhor; ensina-me os teus decretos." },
  { ref: "Salmos 143:8", text: "Faze-me ouvir do teu amor pela manhã, pois em ti confio." },
  { ref: "Isaías 63:9", text: "Em toda a angústia deles, também ele se angustiou, e o anjo da sua presença os salvou; em seu amor e em sua compaixão os redimiu." },
  { ref: "Lamentações 3:22", text: "Graças ao grande amor do Senhor é que não somos consumidos, pois as suas misericórdias não têm fim." },
  { ref: "João 14:21", text: "Quem tem os meus mandamentos e lhes obedece, esse é o que me ama. Quem me ama será amado por meu Pai, e eu também o amarei e me revelarei a ele." },
  { ref: "João 13:34", text: "Um novo mandamento lhes dou: Amem-se uns aos outros. Como eu os amei, vocês devem amar-se uns aos outros." },
  { ref: "João 13:35", text: "Com isso todos saberão que vocês são meus discípulos, se vocês se amarem uns aos outros." }
]
