export interface DialogueVariation {
  openings: string[]
  transitions: string[]
  closings: string[]
}

export const dialogueVariations: DialogueVariation = {
  openings: [
    "Entendo sua dor",
    "Sei que está difícil",
    "Você não está sozinho nessa jornada",
    "Seu coração está pesado",
    "Há luz mesmo na escuridão",
    "Deus vê suas lágrimas",
    "Reconheço o peso que você carrega",
    "Sua luta não passou despercebida",
    "Compreendo o que você está sentindo",
    "Sei o quanto isso tem sido desafiador",
    "Percebo a angústia em seu coração",
    "Sua dor é real e válida",
    "Entendo que você está cansado",
    "Sei que parece impossível agora",
    "Reconheço sua coragem em continuar",
    "Vejo o quanto você tem lutado",
    "Compreendo sua necessidade de paz",
    "Sei que você precisa de força",
    "Entendo sua busca por respostas",
    "Percebo seu desejo de mudança",
    "Reconheço sua fé em meio às dificuldades",
    "Vejo sua esperança mesmo no vale",
    "Compreendo sua necessidade de conforto",
    "Sei que você anseia por alívio",
    "Entendo que você busca direção",
    "Percebo sua sede de renovação",
    "Reconheço seu clamor por ajuda",
    "Vejo suas feridas que precisam de cura",
    "Compreendo sua busca por sentido",
    "Sei que você precisa de um milagre",
    "Entendo sua necessidade de graça",
    "Percebo seu desejo de libertação",
    "Reconheço sua luta contra o desânimo",
    "Vejo que você está exausto",
    "Compreendo sua batalha interior",
    "Sei que você enfrenta tempestades",
    "Entendo que você precisa de sabedoria",
    "Percebo sua necessidade de coragem",
    "Reconheço que você busca propósito",
    "Vejo sua jornada de fé",
    "Compreendo seu momento de provação",
    "Sei que você precisa de restauração",
    "Entendo sua busca por cura emocional",
    "Percebo que você anseia por paz interior",
    "Reconheço sua necessidade de perdão",
    "Vejo que você busca recomeçar",
    "Compreendo seu desejo de transformação",
    "Sei que você precisa de esperança renovada",
    "Entendo sua luta contra a ansiedade",
    "Percebo seu combate ao medo",
    "Reconheço sua batalha pela fé",
    "Vejo que você enfrenta incertezas",
    "Compreendo sua necessidade de clareza",
    "Sei que você busca estabilidade",
    "Entendo que você precisa de firmeza",
    "Percebo sua busca por equilíbrio",
    "Reconheço que você anseia por descanso",
    "Vejo sua necessidade de refrigério",
    "Compreendo seu desejo de alegria",
    "Sei que você busca contentamento",
    "Entendo sua necessidade de gratidão",
    "Percebo que você precisa de ânimo",
    "Reconheço sua busca por motivação",
    "Vejo que você anseia por vitória",
    "Compreendo sua luta por superação",
    "Sei que você busca crescimento",
    "Entendo sua jornada de amadurecimento",
    "Percebo seu processo de santificação",
    "Reconheço sua caminhada com Deus",
    "Vejo que você busca intimidade divina",
    "Compreendo seu desejo de conhecer a Deus",
    "Sei que você anseia por Sua presença",
    "Entendo sua sede do Espírito Santo",
    "Percebo sua fome da Palavra",
    "Reconheço seu coração adorador",
    "Vejo sua vida de oração",
    "Compreendo sua busca por santidade",
    "Sei que você deseja agradar a Deus",
    "Entendo sua entrega ao Senhor",
    "Percebo sua rendição à vontade divina",
    "Reconheço sua confiança em Deus",
    "Vejo sua dependência do Pai",
    "Compreendo sua fé inabalável",
    "Sei que você crê nas promessas",
    "Entendo sua esperança no impossível",
    "Percebo sua certeza da vitória",
    "Reconheço sua convicção em Cristo",
    "Vejo que você está firme na rocha",
    "Compreendo sua perseverança na fé",
    "Sei que você não desiste",
    "Entendo sua resiliência espiritual",
    "Percebo sua força em Deus",
    "Reconheço seu poder através de Cristo",
    "Vejo que você é mais que vencedor",
    "Compreendo sua identidade em Cristo",
    "Sei quem você é no Senhor",
    "Entendo seu valor aos olhos de Deus",
    "Percebo sua importância no Reino",
    "Reconheço seu chamado divino",
    "Vejo seu propósito eterno",
    "Compreendo seu destino em Deus",
    "Sei que você foi escolhido",
    "Entendo que você é amado",
    "Percebo que você é precioso",
    "Reconheço que você é especial",
    "Vejo que você é único",
    "Compreendo que você é filho de Deus",
    "Sei que você é herdeiro do Reino",
    "Entendo que você é templo do Espírito",
    "Percebo que você é luz do mundo",
    "Reconheço que você é sal da terra",
    "Vejo que você é embaixador de Cristo",
    "Compreendo que você é instrumento de Deus",
    "Sei que você é vaso nas mãos do Oleiro",
    "Entendo que você é obra-prima divina",
    "Percebo que você é criação maravilhosa",
    "Reconheço que você é milagre de Deus",
    "Vejo que você é testemunho vivo",
    "Compreendo que você é carta de Cristo",
    "Sei que você é portador da glória",
    "Entendo que você é canal de bênçãos",
    "Percebo que você é semente de esperança",
    "Reconheço que você é agente de mudança",
    "Vejo que você é guerreiro de oração",
    "Compreendo que você é intercessor fiel",
    "Sei que você é adorador verdadeiro",
    "Entendo que você é discípulo dedicado",
    "Percebo que você é servo humilde",
    "Reconheço que você é líder em formação",
    "Vejo que você é profeta da nova geração",
    "Compreendo que você é sacerdote real",
    "Sei que você é nação santa",
    "Entendo que você é povo de propriedade exclusiva",
    "Percebo que você é geração eleita",
    "Reconheço que você é família de Deus",
    "Vejo que você é irmão em Cristo",
    "Compreendo que você é parte do Corpo",
    "Sei que você é membro vital da Igreja",
    "Entendo que você é pedra viva no edifício",
    "Percebo que você é ramo na videira",
    "Reconheço que você é ovelha do rebanho",
    "Vejo que você é amigo de Jesus",
    "Compreendo que você é confidente do Pai",
    "Sei que você é habitação do Altíssimo",
    "Entendo que você é santuário do Espírito",
    "Percebo que você é morada da glória",
    "Reconheço que você é tabernáculo vivo",
    "Vejo que você é altar de adoração",
    "Compreendo que você é incenso suave",
    "Sei que você é perfume de Cristo",
    "Entendo que você é aroma agradável",
    "Percebo que você é fragrância celestial",
  ],

  transitions: [
    "A Palavra de Deus nos lembra que",
    "As Escrituras nos ensinam que",
    "Deus nos diz em Sua Palavra",
    "A Bíblia nos conforta dizendo",
    "Encontramos nas Escrituras",
    "Deus nos assegura que",
    "A Palavra nos revela",
    "As Escrituras Sagradas declaram",
    "Deus promete em Sua Palavra",
    "A Bíblia nos encoraja com",
    "O Senhor nos diz através de",
    "A Palavra Viva proclama",
    "As Sagradas Escrituras afirmam",
    "Deus declara em Sua Palavra",
    "A Bíblia nos ensina que",
    "O Espírito Santo nos revela através de",
    "Encontramos conforto em",
    "A Palavra eterna nos mostra",
    "Deus nos fala através de",
    "As Escrituras nos consolam com",
    "A Bíblia Sagrada nos diz",
    "O Senhor nos assegura em",
    "A Palavra de vida declara",
    "Deus nos encoraja através de",
    "As Escrituras nos fortalecem com",
    "A Bíblia nos promete",
    "O Pai celestial nos diz",
    "A Palavra inspirada revela",
    "Deus nos garante em",
    "As Escrituras nos lembram",
    "A Bíblia nos testifica",
    "O Senhor nos confirma através de",
    "A Palavra profética anuncia",
    "Deus nos instrui em",
    "As Escrituras nos orientam com",
    "A Bíblia nos guia dizendo",
    "O Espírito nos ensina através de",
    "A Palavra santa proclama",
    "Deus nos adverte em",
    "As Escrituras nos exortam",
    "A Bíblia nos aconselha",
    "O Senhor nos direciona através de",
    "A Palavra divina estabelece",
    "Deus nos ordena em",
    "As Escrituras nos comandam",
    "A Bíblia nos determina",
    "O Pai nos instrui através de",
    "A Palavra soberana decreta",
    "Deus nos convida em",
    "As Escrituras nos chamam",
    "A Bíblia nos convoca",
    "O Senhor nos atrai através de",
    "A Palavra amorosa nos alcança",
    "Deus nos busca em",
    "As Escrituras nos encontram",
    "A Bíblia nos resgata com",
    "O Salvador nos liberta através de",
    "A Palavra redentora proclama",
    "Deus nos salva em",
    "As Escrituras nos regeneram",
    "A Bíblia nos transforma com",
    "O Espírito nos renova através de",
    "A Palavra vivificante declara",
    "Deus nos ressuscita em",
    "As Escrituras nos levantam",
    "A Bíblia nos ergue com",
    "O Senhor nos restaura através de",
    "A Palavra curadora anuncia",
    "Deus nos sara em",
    "As Escrituras nos curam",
    "A Bíblia nos recupera com",
    "O Médico dos médicos nos trata através de",
    "A Palavra terapêutica revela",
    "Deus nos fortalece em",
    "As Escrituras nos capacitam",
    "A Bíblia nos equipa com",
    "O Senhor nos prepara através de",
    "A Palavra poderosa declara",
    "Deus nos reveste em",
    "As Escrituras nos armam",
    "A Bíblia nos protege com",
    "O Escudo nos defende através de",
    "A Palavra protetora proclama",
    "Deus nos guarda em",
    "As Escrituras nos preservam",
    "A Bíblia nos mantém com",
    "O Guardião nos vigia através de",
    "A Palavra vigilante anuncia",
    "Deus nos sustenta em",
    "As Escrituras nos apoiam",
    "A Bíblia nos ampara com",
    "O Provedor nos supre através de",
    "A Palavra abundante revela",
    "Deus nos abençoa em",
    "As Escrituras nos prosperam",
    "A Bíblia nos enriquece com",
    "O Doador nos presenteia através de",
    "A Palavra generosa declara",
    "Deus nos multiplica em",
    "As Escrituras nos aumentam",
    "A Bíblia nos expande com",
    "O Senhor nos faz crescer através de",
    "A Palavra frutífera proclama",
    "Deus nos faz produzir em",
    "As Escrituras nos tornam férteis",
    "A Bíblia nos faz florescer com",
    "O Jardineiro nos cultiva através de",
    "A Palavra cultivadora anuncia",
    "Deus nos ilumina em",
    "As Escrituras nos esclarecem",
    "A Bíblia nos revela com",
    "A Luz do mundo nos mostra através de",
    "A Palavra luminosa declara",
    "Deus nos ensina em",
    "As Escrituras nos instruem",
    "A Bíblia nos educa com",
    "O Mestre nos discipula através de",
    "A Palavra pedagógica revela",
    "Deus nos corrige em",
    "As Escrituras nos disciplinam",
    "A Bíblia nos molda com",
    "O Oleiro nos forma através de",
    "A Palavra formadora proclama",
    "Deus nos santifica em",
    "As Escrituras nos purificam",
    "A Bíblia nos limpa com",
    "O Santo nos consagra através de",
    "A Palavra santificadora anuncia",
    "Deus nos justifica em",
    "As Escrituras nos absolvem",
    "A Bíblia nos declara justos com",
    "O Juiz nos inocenta através de",
    "A Palavra justificadora revela",
    "Deus nos glorifica em",
    "As Escrituras nos exaltam",
    "A Bíblia nos honra com",
    "O Rei nos coroa através de",
    "A Palavra gloriosa declara",
    "Deus nos ama em",
    "As Escrituras nos abraçam",
    "A Bíblia nos acolhe com",
    "O Pai nos recebe através de",
    "A Palavra afetuosa proclama",
    "Deus nos perdoa em",
    "As Escrituras nos reconciliam",
    "A Bíblia nos restaura com",
    "O Redentor nos redime através de",
    "A Palavra reconciliadora anuncia",
    "Deus nos adota em",
    "As Escrituras nos fazem filhos",
    "A Bíblia nos torna herdeiros com",
    "O Pai nos acolhe através de",
    "A Palavra adotiva revela",
  ],

  closings: [
    "Que essa verdade traga paz ao seu coração",
    "Confie que Deus está trabalhando em sua vida",
    "Você é amado e cuidado por Deus",
    "Há esperança e renovação à sua frente",
    "Deus tem um propósito em tudo isso",
    "Sua história não termina aqui",
    "Deus está escrevendo algo lindo em sua vida",
    "Mantenha-se firme, pois Deus está com você",
    "Que você encontre força nessa promessa",
    "Lembre-se: você não caminha sozinho",
    "Que essa Palavra ilumine seu caminho",
    "Descanse nessa verdade eterna",
    "Permita que essa promessa cure suas feridas",
    "Deixe essa Palavra renovar sua esperança",
    "Que esse versículo fortaleça sua fé",
    "Agarre-se a essa promessa divina",
    "Medite nessa verdade dia e noite",
    "Guarde essa Palavra em seu coração",
    "Que essa revelação transforme sua vida",
    "Creia nessa promessa com todo seu ser",
    "Declare essa verdade sobre sua situação",
    "Aproprie-se dessa promessa agora",
    "Receba essa Palavra como bálsamo para sua alma",
    "Que essa verdade seja âncora para sua fé",
    "Permita que essa promessa guie seus passos",
    "Deixe essa Palavra ser luz na escuridão",
    "Que esse versículo seja seu escudo",
    "Confie plenamente nessa promessa",
    "Descanse na certeza dessa verdade",
    "Que essa Palavra seja seu fundamento",
    "Apoie-se nessa promessa inabalável",
    "Encontre refúgio nessa verdade eterna",
    "Que essa revelação traga clareza",
    "Permita que essa Palavra cure seu coração",
    "Deixe essa promessa restaurar sua alma",
    "Que esse versículo renove suas forças",
    "Agarre-se a essa verdade nos momentos difíceis",
    "Medite nessa promessa até que penetre profundamente",
    "Guarde essa Palavra como tesouro precioso",
    "Que essa revelação mude sua perspectiva",
    "Creia que Deus cumprirá essa promessa",
    "Declare essa verdade com ousadia",
    "Aproprie-se dessa bênção pela fé",
    "Receba essa Palavra como resposta de Deus",
    "Que essa verdade seja alimento para sua alma",
    "Permita que essa promessa sustente você",
    "Deixe essa Palavra ser sua fortaleza",
    "Que esse versículo seja sua canção",
    "Confie que Deus honrará essa promessa",
    "Descanse na fidelidade dessa verdade",
    "Que essa Palavra seja seu consolo",
    "Apoie-se nessa promessa nos vales",
    "Encontre paz nessa verdade imutável",
    "Que essa revelação liberte você",
    "Permita que essa Palavra quebre correntes",
    "Deixe essa promessa abrir portas",
    "Que esse versículo seja sua vitória",
    "Agarre-se a essa verdade como âncora",
    "Medite nessa promessa constantemente",
    "Guarde essa Palavra em sua mente",
    "Que essa revelação seja seu norte",
    "Creia no poder dessa promessa",
    "Declare essa verdade sobre sua família",
    "Aproprie-se dessa herança espiritual",
    "Receba essa Palavra como profecia",
    "Que essa verdade seja seu escudo protetor",
    "Permita que essa promessa o cubra",
    "Deixe essa Palavra ser sua armadura",
    "Que esse versículo seja sua espada",
    "Confie na autoridade dessa promessa",
    "Descanse no poder dessa verdade",
    "Que essa Palavra seja seu decreto",
    "Apoie-se nessa promessa soberana",
    "Encontre segurança nessa verdade absoluta",
    "Que essa revelação seja seu alicerce",
    "Permita que essa Palavra estabeleça você",
    "Deixe essa promessa firmar seus pés",
    "Que esse versículo seja sua rocha",
    "Agarre-se a essa verdade inabalável",
    "Medite nessa promessa até crer completamente",
    "Guarde essa Palavra como herança",
    "Que essa revelação seja seu legado",
    "Creia na eternidade dessa promessa",
    "Declare essa verdade às gerações",
    "Aproprie-se dessa aliança divina",
    "Receba essa Palavra como pacto",
    "Que essa verdade seja seu compromisso",
    "Permita que essa promessa o vincule a Deus",
    "Deixe essa Palavra selar sua fé",
    "Que esse versículo seja seu juramento",
    "Confie na imutabilidade dessa promessa",
    "Descanse na eternidade dessa verdade",
    "Que essa Palavra seja seu memorial",
    "Apoie-se nessa promessa para sempre",
    "Encontre eternidade nessa verdade",
    "Que essa revelação transcenda o tempo",
    "Permita que essa Palavra seja eterna em você",
    "Deixe essa promessa durar para sempre",
    "Que esse versículo seja perpétuo",
    "Agarre-se a essa verdade eternamente",
    "Medite nessa promessa sem cessar",
    "Guarde essa Palavra para toda vida",
    "Que essa revelação seja seu destino",
    "Creia no cumprimento dessa promessa",
    "Declare essa verdade até se manifestar",
    "Aproprie-se dessa realidade espiritual",
    "Receba essa Palavra como decreto celestial",
    "Que essa verdade seja seu testemunho",
    "Permita que essa promessa seja sua história",
    "Deixe essa Palavra ser seu milagre",
    "Que esse versículo seja sua resposta",
    "Confie que essa promessa se cumprirá",
    "Descanse na certeza dessa verdade",
    "Que essa Palavra seja sua solução",
    "Apoie-se nessa promessa como provisão",
    "Encontre suprimento nessa verdade",
    "Que essa revelação seja sua abundância",
    "Permita que essa Palavra multiplique bênçãos",
    "Deixe essa promessa prosperar você",
    "Que esse versículo seja sua riqueza",
    "Agarre-se a essa verdade como tesouro",
    "Medite nessa promessa até transbordar",
    "Guarde essa Palavra como pérola preciosa",
    "Que essa revelação seja seu investimento eterno",
    "Creia na generosidade dessa promessa",
    "Declare essa verdade sobre suas finanças",
    "Aproprie-se dessa bênção material e espiritual",
    "Receba essa Palavra como cheque assinado",
    "Que essa verdade seja sua provisão diária",
    "Permita que essa promessa supra toda necessidade",
    "Deixe essa Palavra ser seu maná",
    "Que esse versículo seja seu pão de cada dia",
    "Confie que Deus proverá segundo essa promessa",
    "Descanse na suficiência dessa verdade",
    "Que essa Palavra seja sua satisfação",
    "Apoie-se nessa promessa como sustento",
    "Encontre contentamento nessa verdade",
    "Que essa revelação seja sua alegria completa",
    "Permita que essa Palavra encha você de júbilo",
    "Deixe essa promessa ser seu regozijo",
    "Que esse versículo seja seu cântico de louvor",
    "Agarre-se a essa verdade com gratidão",
    "Medite nessa promessa com ação de graças",
    "Guarde essa Palavra com reconhecimento",
    "Que essa revelação seja motivo de celebração",
    "Creia e celebre essa promessa",
    "Declare essa verdade com adoração",
    "Aproprie-se dessa bênção com louvor",
    "Receba essa Palavra com aleluias",
    "Que essa verdade seja seu hino eterno",
  ],
}

export function getRandomOpening(): string {
  return dialogueVariations.openings[Math.floor(Math.random() * dialogueVariations.openings.length)]
}

export function getRandomTransition(): string {
  return dialogueVariations.transitions[Math.floor(Math.random() * dialogueVariations.transitions.length)]
}

export function getRandomClosing(): string {
  return dialogueVariations.closings[Math.floor(Math.random() * dialogueVariations.closings.length)]
}
