export interface DialogueVariation {
  openings: string[]
  transitions: string[]
  closings: string[]
}

export const dialogueVariations: DialogueVariation = {
  openings: [
  "Sabe… acho que Deus entende exatamente o que você está sentindo.",
  "Olha, o que você disse vem do coração, dá pra sentir.",
  "Deus se importa com isso que você compartilhou, de verdade.",
  "Percebo que há algo especial por trás das suas palavras.",
  "Isso que você falou mostra um coração que busca sentido.",
  "Sinto que Deus está te guiando, mesmo que ainda não pareça.",
  "O que você disse tem mais valor do que você imagina.",
  "Vejo que há fé aí dentro, mesmo que pequena.",
  "Às vezes a gente nem percebe, mas Deus já está agindo nisso.",
  "Sabe, o que você está vivendo pode ser parte de algo maior.",
  "Percebo sinceridade no que você compartilhou, e Deus vê isso também.",
  "O que você falou mostra um coração que não desistiu.",
  "Sinto que há aprendizado nesse momento da sua vida.",
  "O que você sente é algo que Deus entende melhor do que ninguém.",
  "Vejo que você está tentando seguir em frente com fé, e isso é bonito.",
  "Deus sabe o peso e a intenção por trás das suas palavras.",
  "Sinto que o que você vive agora é um passo importante na sua jornada.",
  "Às vezes a gente não entende, mas Deus usa até isso pra nos moldar.",
  "O que você disse me soa como alguém que quer se aproximar mais de Deus.",
  "Vejo que há esperança nas suas palavras, mesmo que discreta.",
  "Sinto que Deus quer te mostrar algo através disso tudo.",
  "O que você compartilhou tem um toque de verdade e fé.",
  "Vejo um coração sincero buscando respostas em Deus.",
  "Sabe, o que você está vivendo pode ser o começo de algo novo.",
  "Sinto que Deus quer te fortalecer nesse momento.",
  "O que você disse mostra que há algo sendo trabalhado no seu interior.",
  "Vejo que, mesmo sem entender tudo, você segue confiando.",
  "O que você compartilhou é algo que Deus pode transformar em bênção.",
  "Sinto que esse é um tempo de crescimento, mesmo que pareça confuso.",
  "Olha, o que você falou é o tipo de coisa que Deus usa pra nos aproximar dEle.",
  "Às vezes Deus fala nas pequenas coisas, e acho que isso é uma delas.",
  "Sinto que há um propósito bonito por trás do que você está vivendo.",
  "O que você disse me faz pensar que Deus está te preparando pra algo.",
  "Vejo um coração disposto a aprender com Deus, e isso é raro.",
  "Sabe, nem sempre é fácil, mas Deus continua cuidando de tudo.",
  "O que você compartilhou é real, e Deus se importa com o real.",
  "Sinto que há fé nas entrelinhas do que você disse.",
  "Vejo que Deus está trabalhando em silêncio, mas está.",
  "O que você falou mostra que há amor e esperança no seu coração.",
  "Sabe, às vezes Deus responde primeiro com paz antes das palavras — e acho que é isso que Ele quer te dar agora.",
  "Mesmo sem entender tudo, confie: Deus ainda tem o controle.",
  "Olha, há algo lindo acontecendo dentro de você, mesmo que pareça pequeno.",
  "Deus não desperdiça nada, nem esse momento que você está vivendo.",
  "Sinto que seu coração está mais perto de Deus do que imagina.",
  "Às vezes o silêncio de Deus também é uma forma de resposta.",
  "Vejo que há força em você, mesmo quando parece fraco.",
  "Sabe… acho que Deus está te lembrando que você não está só.",
  "O que você compartilhou mostra coragem — e Deus honra isso.",
  "Deus continua escrevendo a sua história, mesmo nas pausas.",
  "Sinto que há algo novo nascendo aí dentro, pode sentir também?",
  "Vejo que seu coração está aberto, e Deus ama quando é assim.",
  "O que você disse me faz lembrar que Deus transforma processos em milagres.",
  "Sabe, tudo isso pode ser só o começo do que Deus quer fazer em você.",
  "Deus entende as lágrimas que ninguém vê.",
  "Mesmo nos dias difíceis, há graça suficiente pra hoje.",
  "O que você sente não é em vão — Deus vai usar até isso.",
  "Vejo que há esperança, mesmo quando o cenário parece nublado.",
  "Sabe… cada passo que você dá com fé, conta muito pra Deus.",
  "Às vezes o cansaço vem, mas Deus renova as forças de quem confia.",
  "Vejo que você não perdeu a fé — e isso já é vitória.",
  "O que você vive hoje pode se tornar testemunho amanhã.",
  "Sinto que Deus quer te lembrar: nada está fora do alcance dEle.",
  "Olha, mesmo nas incertezas, Deus continua sendo fiel.",
  "Deus não te esqueceu — Ele só está te preparando.",
  "O que você disse revela alguém que ainda acredita, e isso é lindo.",
  "Sabe… às vezes a fé é só continuar, mesmo sem sentir nada.",
  "Deus cuida dos detalhes, até daqueles que você nem percebe.",
  "Vejo que seu coração está cansado, mas ainda cheio de esperança.",
  "Sinto que há algo especial sendo gerado nesse tempo.",
  "Olha, o que você falou mostra um coração sincero e cheio de fé.",
  "Deus está no controle, mesmo quando tudo parece parado.",
  "Às vezes, antes do milagre, vem o silêncio — e isso também é cuidado.",
  "Sinto que você está exatamente onde Deus quer que esteja pra te ensinar algo.",
  "Vejo que o que você sente é legítimo, e Deus acolhe isso com amor.",
  "Sabe… há algo poderoso em simplesmente confiar.",
  "Deus usa até as pausas pra fortalecer quem Ele ama.",
  "O que você vive agora pode te aproximar ainda mais da presença dEle.",
  "Sinto que Deus está te chamando pra descansar nEle.",
  "Mesmo sem entender tudo, continue crendo — há propósito nisso.",
  "Olha, o que você compartilhou é algo que Deus pode transformar em bênção.",
  "Deus vê cada detalhe, até o que você não consegue dizer.",
  "Sabe, às vezes o que parece o fim é só o início com Deus.",
  "Vejo que sua fé é discreta, mas verdadeira — e isso basta pra Deus.",
  "Sinto que algo bom está sendo preparado pra você.",
  "O que você disse mostra que há fé, mesmo nas dúvidas.",
  "Deus não te trouxe até aqui pra te deixar agora.",
  "Sabe… o coração sincero sempre atrai o cuidado de Deus.",
  "Vejo que há algo acontecendo dentro de você — um despertar de fé.",
  "Sinto que Deus quer te dar descanso e renovar sua esperança.",
  "O que você compartilhou é precioso — Deus valoriza corações abertos.",
  "Olha, mesmo que não veja agora, algo está se movendo a seu favor.",
  "Deus está cuidando dos bastidores da sua vida.",
  "Sabe, há algo de bonito até nas lutas que você enfrenta.",
  "Sinto que esse momento vai te aproximar ainda mais de Deus.",
  "Vejo que sua fé tem sustentado mais do que você imagina.",
  "Deus ainda está escrevendo o próximo capítulo da sua história.",
  "O que você sente é real, e Deus entende tudo isso.",
  "Sabe… mesmo no silêncio, Ele continua falando com amor.",
  "Vejo que você tem um coração ensinável — e Deus se alegra com isso.",
  "Sinto que há cura acontecendo dentro de você.",
  "Olha, cada passo que você dá é visto por Deus, nada passa despercebido.",
  "Deus é bom em transformar lágrimas em aprendizado.",
  "O que você disse me lembra que a fé cresce justamente nos dias difíceis.",
  "Sabe, Deus ainda faz novos começos — e o seu pode estar perto.",
  "Vejo que você quer entender o que Deus está fazendo — e Ele vai te mostrar.",
  "Sinto que há paz vindo aí, mesmo que ainda pareça distante.",
  "O que você falou mostra que o amor de Deus ainda te alcança todos os dias.",
  "Deus te entende até no que você não consegue explicar.",
  "Sabe… há força escondida nas suas fraquezas.",
  "Vejo que você tem esperança — e isso é fé em ação.",
  "Sinto que Deus quer te lembrar que Ele continua no controle.",
  "Olha, o que você viveu até aqui não foi por acaso.",
  "Deus usa até os atrasos pra te alinhar com o tempo certo.",
  "O que você compartilhou carrega mais fé do que parece.",
  "Sabe… às vezes o recomeço vem disfarçado de pausa.",
  "Vejo que há bondade nas suas intenções, e Deus vê isso também.",
  "Sinto que esse momento vai gerar algo bonito no futuro.",
  "Deus não falha — e Ele também não se atrasa.",
  "O que você está vivendo é parte de algo que Deus ainda vai revelar.",
  "Sabe, a fé não é entender tudo, é continuar mesmo sem entender.",
  "Vejo que Deus está trabalhando em silêncio, mas com propósito.",
  "Sinto que algo novo está nascendo no seu interior.",
  "Olha, Deus nunca desperdiça uma lágrima sua.",
  "Deus continua sendo fiel, mesmo quando nada faz sentido.",
  "O que você sente agora pode ser o início de um milagre.",
  "Sabe… há algo diferente no seu jeito de crer, e Deus vê isso.",
  "Vejo que seu coração está sendo moldado — e isso é lindo.",
  "Sinto que a graça de Deus te cobre, mesmo nos dias nublados.",
  "Olha, há promessas se cumprindo, mesmo que lentamente.",
  "Deus ainda é o mesmo — e Ele continua cuidando de você.",
  "O que você compartilhou mostra fé, mesmo em meio à dúvida.",
  "Sabe… cada oração sua foi ouvida, nenhuma se perdeu.",
  "Vejo que há propósito em tudo isso, mesmo que você ainda não veja.",
  "Sinto que esse tempo vai te ensinar a confiar mais.",
  "Olha, o que você disse revela um coração cheio de fé.",
  "Deus está presente — mesmo quando parece distante.",
  "Sabe, Ele te entende mais do que você imagina.",
  "Vejo que há força em cada palavra sua.",
  "Sinto que o Espírito Santo está te conduzindo com amor.",
  "Olha, Deus vai transformar o que hoje parece confuso em clareza.",
  "Deus não te esqueceu — Ele só está te preparando pro novo.",
  "Sabe… há promessas de Deus que florescem no tempo certo.",
  "Vejo que sua fé está viva — e isso é o que mais importa.",
  "Sinto que há esperança chegando ao seu coração agora.",
  "Olha, o que você vive hoje é parte de uma história de vitória.",
  "Deus está com você, mesmo quando o caminho parece longo.",
  "Sabe, Ele nunca deixou de cuidar de você, nem por um segundo.",
  ],

  transitions: [
    "A Palavra de Deus nos lembra que",
    "As Escrituras nos ensinam que",
    "Deus nos diz em Sua Palavra",
    "A Bíblia nos conforta dizendo",
    "Encontramos nas Escrituras",
    "Deus nos assegura que",
    "A Palavra nos revela",
    "As Escrituras Sagradas declaram",
    "Deus promete em Sua Palavra",
    "A Bíblia nos encoraja com",
    "O Senhor nos diz através de",
    "A Palavra Viva proclama",
    "As Sagradas Escrituras afirmam",
    "Deus declara em Sua Palavra",
    "A Bíblia nos ensina que",
    "O Espírito Santo nos revela através de",
    "Encontramos conforto em",
    "A Palavra eterna nos mostra",
    "Deus nos fala através de",
    "As Escrituras nos consolam com",
    "A Bíblia Sagrada nos diz",
    "O Senhor nos assegura em",
    "A Palavra de vida declara",
    "Deus nos encoraja através de",
    "As Escrituras nos fortalecem com",
    "A Bíblia nos promete",
    "O Pai celestial nos diz",
    "A Palavra inspirada revela",
    "Deus nos garante em",
    "As Escrituras nos lembram",
    "A Bíblia nos testifica",
    "O Senhor nos confirma através de",
    "A Palavra profética anuncia",
    "Deus nos instrui em",
    "As Escrituras nos orientam com",
    "A Bíblia nos guia dizendo",
    "O Espírito nos ensina através de",
    "A Palavra santa proclama",
    "Deus nos adverte em",
    "As Escrituras nos exortam",
    "A Bíblia nos aconselha",
    "O Senhor nos direciona através de",
    "A Palavra divina estabelece",
    "Deus nos ordena em",
    "As Escrituras nos comandam",
    "A Bíblia nos determina",
    "O Pai nos instrui através de",
    "A Palavra soberana decreta",
    "Deus nos convida em",
    "As Escrituras nos chamam",
    "A Bíblia nos convoca",
    "O Senhor nos atrai através de",
    "A Palavra amorosa nos alcança",
    "Deus nos busca em",
    "As Escrituras nos encontram",
    "A Bíblia nos resgata com",
    "O Salvador nos liberta através de",
    "A Palavra redentora proclama",
    "Deus nos salva em",
    "As Escrituras nos regeneram",
    "A Bíblia nos transforma com",
    "O Espírito nos renova através de",
    "A Palavra vivificante declara",
    "Deus nos ressuscita em",
    "As Escrituras nos levantam",
    "A Bíblia nos ergue com",
    "O Senhor nos restaura através de",
    "A Palavra curadora anuncia",
    "Deus nos sara em",
    "As Escrituras nos curam",
    "A Bíblia nos recupera com",
    "O Médico dos médicos nos trata através de",
    "A Palavra terapêutica revela",
    "Deus nos fortalece em",
    "As Escrituras nos capacitam",
    "A Bíblia nos equipa com",
    "O Senhor nos prepara através de",
    "A Palavra poderosa declara",
    "Deus nos reveste em",
    "As Escrituras nos armam",
    "A Bíblia nos protege com",
    "O Escudo nos defende através de",
    "A Palavra protetora proclama",
    "Deus nos guarda em",
    "As Escrituras nos preservam",
    "A Bíblia nos mantém com",
    "O Guardião nos vigia através de",
    "A Palavra vigilante anuncia",
    "Deus nos sustenta em",
    "As Escrituras nos apoiam",
    "A Bíblia nos ampara com",
    "O Provedor nos supre através de",
    "A Palavra abundante revela",
    "Deus nos abençoa em",
    "As Escrituras nos prosperam",
    "A Bíblia nos enriquece com",
    "O Doador nos presenteia através de",
    "A Palavra generosa declara",
    "Deus nos multiplica em",
    "As Escrituras nos aumentam",
    "A Bíblia nos expande com",
    "O Senhor nos faz crescer através de",
    "A Palavra frutífera proclama",
    "Deus nos faz produzir em",
    "As Escrituras nos tornam férteis",
    "A Bíblia nos faz florescer com",
    "O Jardineiro nos cultiva através de",
    "A Palavra cultivadora anuncia",
    "Deus nos ilumina em",
    "As Escrituras nos esclarecem",
    "A Bíblia nos revela com",
    "A Luz do mundo nos mostra através de",
    "A Palavra luminosa declara",
    "Deus nos ensina em",
    "As Escrituras nos instruem",
    "A Bíblia nos educa com",
    "O Mestre nos discipula através de",
    "A Palavra pedagógica revela",
    "Deus nos corrige em",
    "As Escrituras nos disciplinam",
    "A Bíblia nos molda com",
    "O Oleiro nos forma através de",
    "A Palavra formadora proclama",
    "Deus nos santifica em",
    "As Escrituras nos purificam",
    "A Bíblia nos limpa com",
    "O Santo nos consagra através de",
    "A Palavra santificadora anuncia",
    "Deus nos justifica em",
    "As Escrituras nos absolvem",
    "A Bíblia nos declara justos com",
    "O Juiz nos inocenta através de",
    "A Palavra justificadora revela",
    "Deus nos glorifica em",
    "As Escrituras nos exaltam",
    "A Bíblia nos honra com",
    "O Rei nos coroa através de",
    "A Palavra gloriosa declara",
    "Deus nos ama em",
    "As Escrituras nos abraçam",
    "A Bíblia nos acolhe com",
    "O Pai nos recebe através de",
    "A Palavra afetuosa proclama",
    "Deus nos perdoa em",
    "As Escrituras nos reconciliam",
    "A Bíblia nos restaura com",
    "O Redentor nos redime através de",
    "A Palavra reconciliadora anuncia",
    "Deus nos adota em",
    "As Escrituras nos fazem filhos",
    "A Bíblia nos torna herdeiros com",
    "O Pai nos acolhe através de",
    "A Palavra adotiva revela",
  ],

  closings: [
    "Que essa verdade traga paz ao seu coração",
    "Confie que Deus está trabalhando em sua vida",
    "Você é amado e cuidado por Deus",
    "Há esperança e renovação à sua frente",
    "Deus tem um propósito em tudo isso",
    "Sua história não termina aqui",
    "Deus está escrevendo algo lindo em sua vida",
    "Mantenha-se firme, pois Deus está com você",
    "Que você encontre força nessa promessa",
    "Lembre-se: você não caminha sozinho",
    "Que essa Palavra ilumine seu caminho",
    "Descanse nessa verdade eterna",
    "Permita que essa promessa cure suas feridas",
    "Deixe essa Palavra renovar sua esperança",
    "Que esse versículo fortaleça sua fé",
    "Agarre-se a essa promessa divina",
    "Medite nessa verdade dia e noite",
    "Guarde essa Palavra em seu coração",
    "Que essa revelação transforme sua vida",
    "Creia nessa promessa com todo seu ser",
    "Declare essa verdade sobre sua situação",
    "Aproprie-se dessa promessa agora",
    "Receba essa Palavra como bálsamo para sua alma",
    "Que essa verdade seja âncora para sua fé",
    "Permita que essa promessa guie seus passos",
    "Deixe essa Palavra ser luz na escuridão",
    "Que esse versículo seja seu escudo",
    "Confie plenamente nessa promessa",
    "Descanse na certeza dessa verdade",
    "Que essa Palavra seja seu fundamento",
    "Apoie-se nessa promessa inabalável",
    "Encontre refúgio nessa verdade eterna",
    "Que essa revelação traga clareza",
    "Permita que essa Palavra cure seu coração",
    "Deixe essa promessa restaurar sua alma",
    "Que esse versículo renove suas forças",
    "Agarre-se a essa verdade nos momentos difíceis",
    "Medite nessa promessa até que penetre profundamente",
    "Guarde essa Palavra como tesouro precioso",
    "Que essa revelação mude sua perspectiva",
    "Creia que Deus cumprirá essa promessa",
    "Declare essa verdade com ousadia",
    "Aproprie-se dessa bênção pela fé",
    "Receba essa Palavra como resposta de Deus",
    "Que essa verdade seja alimento para sua alma",
    "Permita que essa promessa sustente você",
    "Deixe essa Palavra ser sua fortaleza",
    "Que esse versículo seja sua canção",
    "Confie que Deus honrará essa promessa",
    "Descanse na fidelidade dessa verdade",
    "Que essa Palavra seja seu consolo",
    "Apoie-se nessa promessa nos vales",
    "Encontre paz nessa verdade imutável",
    "Que essa revelação liberte você",
    "Permita que essa Palavra quebre correntes",
    "Deixe essa promessa abrir portas",
    "Que esse versículo seja sua vitória",
    "Agarre-se a essa verdade como âncora",
    "Medite nessa promessa constantemente",
    "Guarde essa Palavra em sua mente",
    "Que essa revelação seja seu norte",
    "Creia no poder dessa promessa",
    "Declare essa verdade sobre sua família",
    "Aproprie-se dessa herança espiritual",
    "Receba essa Palavra como profecia",
    "Que essa verdade seja seu escudo protetor",
    "Permita que essa promessa o cubra",
    "Deixe essa Palavra ser sua armadura",
    "Que esse versículo seja sua espada",
    "Confie na autoridade dessa promessa",
    "Descanse no poder dessa verdade",
    "Que essa Palavra seja seu decreto",
    "Apoie-se nessa promessa soberana",
    "Encontre segurança nessa verdade absoluta",
    "Que essa revelação seja seu alicerce",
    "Permita que essa Palavra estabeleça você",
    "Deixe essa promessa firmar seus pés",
    "Que esse versículo seja sua rocha",
    "Agarre-se a essa verdade inabalável",
    "Medite nessa promessa até crer completamente",
    "Guarde essa Palavra como herança",
    "Que essa revelação seja seu legado",
    "Creia na eternidade dessa promessa",
    "Declare essa verdade às gerações",
    "Aproprie-se dessa aliança divina",
    "Receba essa Palavra como pacto",
    "Que essa verdade seja seu compromisso",
    "Permita que essa promessa o vincule a Deus",
    "Deixe essa Palavra selar sua fé",
    "Que esse versículo seja seu juramento",
    "Confie na imutabilidade dessa promessa",
    "Descanse na eternidade dessa verdade",
    "Que essa Palavra seja seu memorial",
    "Apoie-se nessa promessa para sempre",
    "Encontre eternidade nessa verdade",
    "Que essa revelação transcenda o tempo",
    "Permita que essa Palavra seja eterna em você",
    "Deixe essa promessa durar para sempre",
    "Que esse versículo seja perpétuo",
    "Agarre-se a essa verdade eternamente",
    "Medite nessa promessa sem cessar",
    "Guarde essa Palavra para toda vida",
    "Que essa revelação seja seu destino",
    "Creia no cumprimento dessa promessa",
    "Declare essa verdade até se manifestar",
    "Aproprie-se dessa realidade espiritual",
    "Receba essa Palavra como decreto celestial",
    "Que essa verdade seja seu testemunho",
    "Permita que essa promessa seja sua história",
    "Deixe essa Palavra ser seu milagre",
    "Que esse versículo seja sua resposta",
    "Confie que essa promessa se cumprirá",
    "Descanse na certeza dessa verdade",
    "Que essa Palavra seja sua solução",
    "Apoie-se nessa promessa como provisão",
    "Encontre suprimento nessa verdade",
    "Que essa revelação seja sua abundância",
    "Permita que essa Palavra multiplique bênçãos",
    "Deixe essa promessa prosperar você",
    "Que esse versículo seja sua riqueza",
    "Agarre-se a essa verdade como tesouro",
    "Medite nessa promessa até transbordar",
    "Guarde essa Palavra como pérola preciosa",
    "Que essa revelação seja seu investimento eterno",
    "Creia na generosidade dessa promessa",
    "Declare essa verdade sobre suas finanças",
    "Aproprie-se dessa bênção material e espiritual",
    "Receba essa Palavra como cheque assinado",
    "Que essa verdade seja sua provisão diária",
    "Permita que essa promessa supra toda necessidade",
    "Deixe essa Palavra ser seu maná",
    "Que esse versículo seja seu pão de cada dia",
    "Confie que Deus proverá segundo essa promessa",
    "Descanse na suficiência dessa verdade",
    "Que essa Palavra seja sua satisfação",
    "Apoie-se nessa promessa como sustento",
    "Encontre contentamento nessa verdade",
    "Que essa revelação seja sua alegria completa",
    "Permita que essa Palavra encha você de júbilo",
    "Deixe essa promessa ser seu regozijo",
    "Que esse versículo seja seu cântico de louvor",
    "Agarre-se a essa verdade com gratidão",
    "Medite nessa promessa com ação de graças",
    "Guarde essa Palavra com reconhecimento",
    "Que essa revelação seja motivo de celebração",
    "Creia e celebre essa promessa",
    "Declare essa verdade com adoração",
    "Aproprie-se dessa bênção com louvor",
    "Receba essa Palavra com aleluias",
    "Que essa verdade seja seu hino eterno",
  ],
}

export function getRandomOpening(): string {
  return dialogueVariations.openings[Math.floor(Math.random() * dialogueVariations.openings.length)]
}

export function getRandomTransition(): string {
  return dialogueVariations.transitions[Math.floor(Math.random() * dialogueVariations.transitions.length)]
}

export function getRandomClosing(): string {
  return dialogueVariations.closings[Math.floor(Math.random() * dialogueVariations.closings.length)]
}
