import {
  type LucideIcon,
  Heart,
  Cloud,
  HelpCircle,
  Sparkles,
  Frown,
  Zap,
  HandHeart,
  AlertCircle,
  HeartCrack,
  Star,
  Flame,
  Brain,
  Leaf,
  Target,
  CloudRain,
  Rainbow,
  Battery,
  Shield,
  Lightbulb,
  Move as Dove,
  Flower2,
  Bolt,
  Gift,
  Moon,
  File as Fire,
  Sun,
  Sparkle,
  Music,
  Waves,
  Battery as Butterfly,
  Mountain,
  Flower,
  StarOff,
  Palette,
  Sprout,
  Smile,
  Bell,
  Sunrise,
  Drama,
  Trophy,
  Globe,
  BookOpen,
  Users,
  DollarSign,
  HomeIcon,
  GraduationCap,
  Cross,
  Scale,
  Focus,
  Heading as Seedling,
  PartyPopper,
  CircleDot,
  Church,
} from "lucide-react"

export interface Theme {
  icon: LucideIcon
  label: string
  prompt: string
  color: string
}

export const allThemes: Theme[] = [
  {
    icon: Cloud,
    label: "Sentindo Ansiedade",
    prompt: "Estou sentindo ansiedade",
    color: "bg-blue-500/5 hover:bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20",
  },
  {
    icon: Sparkles,
    label: "Preciso de Encorajamento",
    prompt: "Preciso de encorajamento",
    color: "bg-purple-500/5 hover:bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20",
  },
  {
    icon: HelpCircle,
    label: "Dúvidas Espirituais",
    prompt: "Tenho dúvidas espirituais",
    color: "bg-amber-500/5 hover:bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20",
  },
  {
    icon: Heart,
    label: "Gratidão e Paz",
    prompt: "Quero expressar gratidão",
    color: "bg-rose-500/5 hover:bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20",
  },
  {
    icon: Frown,
    label: "Estou Triste",
    prompt: "Estou me sentindo triste",
    color: "bg-indigo-500/5 hover:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20",
  },
  {
    icon: Zap,
    label: "Preciso de Força",
    prompt: "Preciso de força para continuar",
    color: "bg-red-500/5 hover:bg-red-500/10 text-red-600 dark:text-red-400 border border-red-500/20",
  },
  {
    icon: HandHeart,
    label: "Momento de Oração",
    prompt: "Quero um momento de oração",
    color: "bg-teal-500/5 hover:bg-teal-500/10 text-teal-600 dark:text-teal-400 border border-teal-500/20",
  },
  {
    icon: AlertCircle,
    label: "Sentindo Medo",
    prompt: "Estou com medo",
    color: "bg-orange-500/5 hover:bg-orange-500/10 text-orange-600 dark:text-orange-400 border border-orange-500/20",
  },
  {
    icon: HeartCrack,
    label: "Coração Partido",
    prompt: "Meu coração está partido",
    color: "bg-pink-500/5 hover:bg-pink-500/10 text-pink-600 dark:text-pink-400 border border-pink-500/20",
  },
  {
    icon: Star,
    label: "Busco Esperança",
    prompt: "Preciso de esperança",
    color: "bg-yellow-500/5 hover:bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border border-yellow-500/20",
  },
  {
    icon: Flame,
    label: "Estou com Raiva",
    prompt: "Estou sentindo raiva",
    color: "bg-red-600/5 hover:bg-red-600/10 text-red-700 dark:text-red-400 border border-red-600/20",
  },
  {
    icon: Brain,
    label: "Confuso sobre o Futuro",
    prompt: "Estou confuso sobre meu futuro",
    color: "bg-slate-500/5 hover:bg-slate-500/10 text-slate-600 dark:text-slate-400 border border-slate-500/20",
  },
  {
    icon: Leaf,
    label: "Busco Paz Interior",
    prompt: "Quero encontrar paz interior",
    color: "bg-green-500/5 hover:bg-green-500/10 text-green-600 dark:text-green-400 border border-green-500/20",
  },
  {
    icon: Target,
    label: "Preciso de Direção",
    prompt: "Preciso de direção na vida",
    color: "bg-cyan-500/5 hover:bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border border-cyan-500/20",
  },
  {
    icon: CloudRain,
    label: "Pensamentos Negativos",
    prompt: "Tenho pensamentos negativos",
    color: "bg-gray-500/5 hover:bg-gray-500/10 text-gray-600 dark:text-gray-400 border border-gray-500/20",
  },
  {
    icon: Rainbow,
    label: "Quero Alegria",
    prompt: "Quero sentir alegria",
    color: "bg-violet-500/5 hover:bg-violet-500/10 text-violet-600 dark:text-violet-400 border border-violet-500/20",
  },
  {
    icon: Battery,
    label: "Estou Cansado",
    prompt: "Estou muito cansado",
    color: "bg-stone-500/5 hover:bg-stone-500/10 text-stone-600 dark:text-stone-400 border border-stone-500/20",
  },
  {
    icon: Shield,
    label: "Preciso de Proteção",
    prompt: "Preciso de proteção divina",
    color: "bg-blue-600/5 hover:bg-blue-600/10 text-blue-700 dark:text-blue-400 border border-blue-600/20",
  },
  {
    icon: Lightbulb,
    label: "Busco Sabedoria",
    prompt: "Preciso de sabedoria",
    color: "bg-amber-600/5 hover:bg-amber-600/10 text-amber-700 dark:text-amber-400 border border-amber-600/20",
  },
  {
    icon: Dove,
    label: "Perdão e Reconciliação",
    prompt: "Preciso aprender a perdoar",
    color: "bg-sky-500/5 hover:bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20",
  },
  {
    icon: Flower2,
    label: "Renovação Espiritual",
    prompt: "Quero renovação espiritual",
    color:
      "bg-fuchsia-500/5 hover:bg-fuchsia-500/10 text-fuchsia-600 dark:text-fuchsia-400 border border-fuchsia-500/20",
  },
  {
    icon: Bolt,
    label: "Preciso de Coragem",
    prompt: "Preciso de coragem",
    color: "bg-yellow-600/5 hover:bg-yellow-600/10 text-yellow-700 dark:text-yellow-400 border border-yellow-600/20",
  },
  {
    icon: Gift,
    label: "Gratidão pelas Bênçãos",
    prompt: "Quero agradecer pelas bênçãos",
    color:
      "bg-emerald-500/5 hover:bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20",
  },
  {
    icon: Moon,
    label: "Insônia e Descanso",
    prompt: "Não consigo dormir",
    color: "bg-indigo-600/5 hover:bg-indigo-600/10 text-indigo-700 dark:text-indigo-400 border border-indigo-600/20",
  },
  {
    icon: Fire,
    label: "Avivamento Espiritual",
    prompt: "Quero avivamento espiritual",
    color: "bg-orange-600/5 hover:bg-orange-600/10 text-orange-700 dark:text-orange-400 border border-orange-600/20",
  },
  {
    icon: Sun,
    label: "Crescimento Pessoal",
    prompt: "Quero crescer espiritualmente",
    color: "bg-lime-500/5 hover:bg-lime-500/10 text-lime-600 dark:text-lime-400 border border-lime-500/20",
  },
  {
    icon: Sparkle,
    label: "Propósito de Vida",
    prompt: "Qual é meu propósito?",
    color: "bg-purple-600/5 hover:bg-purple-600/10 text-purple-700 dark:text-purple-400 border border-purple-600/20",
  },
  {
    icon: Music,
    label: "Louvor e Adoração",
    prompt: "Quero um momento de louvor",
    color: "bg-pink-600/5 hover:bg-pink-600/10 text-pink-700 dark:text-pink-400 border border-pink-600/20",
  },
  {
    icon: Waves,
    label: "Superando Dificuldades",
    prompt: "Estou passando por dificuldades",
    color: "bg-teal-600/5 hover:bg-teal-600/10 text-teal-700 dark:text-teal-400 border border-teal-600/20",
  },
  {
    icon: Butterfly,
    label: "Transformação",
    prompt: "Quero ser transformado",
    color: "bg-violet-600/5 hover:bg-violet-600/10 text-violet-700 dark:text-violet-400 border border-violet-600/20",
  },
  {
    icon: Mountain,
    label: "Fé em Tempos Difíceis",
    prompt: "Preciso de fé",
    color: "bg-slate-600/5 hover:bg-slate-600/10 text-slate-700 dark:text-slate-400 border border-slate-600/20",
  },
  {
    icon: Flower,
    label: "Amor de Deus",
    prompt: "Quero sentir o amor de Deus",
    color: "bg-rose-600/5 hover:bg-rose-600/10 text-rose-700 dark:text-rose-400 border border-rose-600/20",
  },
  {
    icon: StarOff,
    label: "Milagres e Maravilhas",
    prompt: "Preciso de um milagre",
    color: "bg-cyan-600/5 hover:bg-cyan-600/10 text-cyan-700 dark:text-cyan-400 border border-cyan-600/20",
  },
  {
    icon: Palette,
    label: "Criatividade e Dons",
    prompt: "Quero desenvolver meus dons",
    color:
      "bg-fuchsia-600/5 hover:bg-fuchsia-600/10 text-fuchsia-700 dark:text-fuchsia-400 border border-fuchsia-600/20",
  },
  {
    icon: Sprout,
    label: "Cura Interior",
    prompt: "Preciso de cura interior",
    color: "bg-green-600/5 hover:bg-green-600/10 text-green-700 dark:text-green-400 border border-green-600/20",
  },
  {
    icon: Smile,
    label: "Alegria no Senhor",
    prompt: "Quero alegria no Senhor",
    color: "bg-amber-500/5 hover:bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20",
  },
  {
    icon: Bell,
    label: "Chamado e Vocação",
    prompt: "Qual é meu chamado?",
    color: "bg-blue-500/5 hover:bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20",
  },
  {
    icon: Sunrise,
    label: "Novo Começo",
    prompt: "Quero um novo começo",
    color: "bg-orange-500/5 hover:bg-orange-500/10 text-orange-600 dark:text-orange-400 border border-orange-500/20",
  },
  {
    icon: Drama,
    label: "Identidade em Cristo",
    prompt: "Quem sou eu em Cristo?",
    color: "bg-purple-500/5 hover:bg-purple-500/10 text-purple-600 dark:text-purple-400 border border-purple-500/20",
  },
  {
    icon: Trophy,
    label: "Vitória Espiritual",
    prompt: "Quero vitória espiritual",
    color: "bg-yellow-500/5 hover:bg-yellow-500/10 text-yellow-600 dark:text-yellow-400 border border-yellow-500/20",
  },
  {
    icon: Globe,
    label: "Missões e Evangelismo",
    prompt: "Quero evangelizar",
    color: "bg-teal-500/5 hover:bg-teal-500/10 text-teal-600 dark:text-teal-400 border border-teal-500/20",
  },
  {
    icon: BookOpen,
    label: "Entendendo a Bíblia",
    prompt: "Quero entender a Bíblia",
    color: "bg-indigo-500/5 hover:bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20",
  },
  {
    icon: Users,
    label: "Relacionamentos",
    prompt: "Preciso de ajuda nos relacionamentos",
    color: "bg-pink-500/5 hover:bg-pink-500/10 text-pink-600 dark:text-pink-400 border border-pink-500/20",
  },
  {
    icon: DollarSign,
    label: "Finanças e Provisão",
    prompt: "Preciso de provisão financeira",
    color:
      "bg-emerald-600/5 hover:bg-emerald-600/10 text-emerald-700 dark:text-emerald-400 border border-emerald-600/20",
  },
  {
    icon: HomeIcon,
    label: "Família e Lar",
    prompt: "Preciso de sabedoria para minha família",
    color: "bg-rose-500/5 hover:bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20",
  },
  {
    icon: Target,
    label: "Trabalho e Carreira",
    prompt: "Preciso de direção no trabalho",
    color: "bg-slate-500/5 hover:bg-slate-500/10 text-slate-600 dark:text-slate-400 border border-slate-500/20",
  },
  {
    icon: GraduationCap,
    label: "Estudos e Aprendizado",
    prompt: "Preciso de sabedoria nos estudos",
    color: "bg-blue-500/5 hover:bg-blue-500/10 text-blue-600 dark:text-blue-400 border border-blue-500/20",
  },
  {
    icon: Cross,
    label: "Saúde e Cura",
    prompt: "Preciso de cura física",
    color: "bg-red-500/5 hover:bg-red-500/10 text-red-600 dark:text-red-400 border border-red-500/20",
  },
  {
    icon: Scale,
    label: "Justiça e Verdade",
    prompt: "Busco justiça",
    color: "bg-gray-600/5 hover:bg-gray-600/10 text-gray-700 dark:text-gray-400 border border-gray-600/20",
  },
  {
    icon: Focus,
    label: "Foco e Disciplina",
    prompt: "Preciso de disciplina",
    color: "bg-cyan-500/5 hover:bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border border-cyan-500/20",
  },
  {
    icon: Seedling,
    label: "Paciência e Espera",
    prompt: "Preciso aprender a esperar",
    color: "bg-lime-600/5 hover:bg-lime-600/10 text-lime-700 dark:text-lime-400 border border-lime-600/20",
  },
  {
    icon: PartyPopper,
    label: "Celebração e Vitória",
    prompt: "Quero celebrar as vitórias",
    color:
      "bg-fuchsia-500/5 hover:bg-fuchsia-500/10 text-fuchsia-600 dark:text-fuchsia-400 border border-fuchsia-500/20",
  },
  {
    icon: CircleDot,
    label: "Meditação e Quietude",
    prompt: "Quero um momento de quietude",
    color: "bg-violet-500/5 hover:bg-violet-500/10 text-violet-600 dark:text-violet-400 border border-violet-500/20",
  },
  {
    icon: Church,
    label: "Presença de Deus",
    prompt: "Quero sentir a presença de Deus",
    color: "bg-amber-600/5 hover:bg-amber-600/10 text-amber-700 dark:text-amber-400 border border-amber-600/20",
  },
]

export function getRandomThemes(count = 4): Theme[] {
  const shuffled = [...allThemes].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
